name: RDP

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok.

      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/bayuaji1212/RDP-WIN10/blob/78ac51edd75f636cfa9640b020afb447b76d8c3e/resources/start.bat -OutFile start.bat
        Invoke-WebRequest https://github.com/bayuaji1212/rdp6jam/blob/1814fd92bd92cdb7982e741e3d56ce7a2753a6a3/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://github.com/bayuaji1212/RDP-WIN10/blob/78ac51edd75f636cfa9640b020afb447b76d8c3e/resources/loop.ps1 -OutFile loop.bat
        Invoke-WebRequest https://github.com/bayuaji1212/RDP-WIN10/blob/78ac51edd75f636cfa9640b020afb447b76d8c3e/resources/start.bat -OutFile push.bat
    - name: Extract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Windows10 RDP.

      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect RDP.

      run: cmd /c start.bat

    - name: win10 RDP.

      run: cmd /c loop.bat
